recommend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('songs/', include('song.urls')),
]

songs/urls.py
from django.urls import path
from . import views


app_name = 'songs'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('create/', views.create, name = 'create'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('update/<int:pk>/', views.update, name = 'update'),
    path('delete/', views.delete, name = 'delete'),
]

songs/models.py
from django.db import models

# Create your models here.
class Song(models.Model):
    title = models.CharField(max_length=20)
    artist = models.CharField(max_length=20)
    description = models.TextField()
    created_at= models.DateTimeField(auto_now_add=True)

songs/forms.py
from django import forms
from .models import Song

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = '__all__'
        

songs/views.py
from django.shortcuts import render, redirect
from .models import Song
from .forms import SongForm

# Create your views here.
def index(request):
    songs = Song.objects.all()
    context = {
        'songs' : songs
    }
    
    return render(request, 'songs/index.html', context)

def create(request):
    if request.method == 'POST':
        form = SongForm(request.POST)
        if form.is_valid():
            song = form.save()
            return redirect('songs:detail', song.pk)
    # new
    else:
        form = SongForm()
    context = {
        'form' : form
    }
    return render(request, 'create.html', context)
        
def detail(request, pk):
    song = Song.objects.get(pk=pk)
    context = {
        'song' : song
    }
    return render(request, 'songs/detail.html', context)
    
    
def update(request, pk):
    song = Song.objects.get(pk=pk)
    if request.method =='POST':
        form = SongForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('songs:detail', song.pk)
    
    else:
        form = SongForm()
    context = {
        'song' : song,
        'form' : form
    }
    return render(request, 'songs/update.html', context)

def delete(request, pk):
    song = Song.objects.get(pk=pk)
    song.delete()
    return redirect('songs:index')
    

songs/templates/songs/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>등록 페이지</h1>
    <form action="{% url "songs:create" %}" method = 'POST'>
        {% csrf_token %}
     
    
        <p>제목 : {{ form.title }}</p>
        <p>아티스트 : {{ form.artist }}</p>
        <p>곡 정보 : {{ form.content}}</p>

    
    <input type="submit" value = '제출'>
    </form>
</body>
</html>

songs/templates/songs/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>상세 페이지</h1>
    <h2>제목: {{ song.title }}</h2>
    <p>아티스트: {{ song.artist }}</p>
    <p>곡 정보: {{ song.description }}</p>
    <p>등록일: {{ song.created_at }}</p>

    <form action="{% url "songs:index" %}">
        <input type="submit" value = '목록 보기'>
    </form>
    <form action="{% url "songs:update" song.pk %}">
        <input type="submit" value = '수정'>
    </form>
    <form action="{% url "songs:delete" song.pk %}">
        <input type="submit" value = '삭제'>
    </form>
</body>
</html>

songs/templates/songs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>음악 공유 사이트</h1>
    <form action="{% url "songs:create" %} " method = 'GET'>
        <input type="submit" value = '등록'>
    </form>
    {% for song in songs %}
        <p>제목: {{song.title}}</p>
        <p>아티스트: {{ song.artist }}</p>
        <a href="{% url "songs:detail" song.pk %}">자세히</a>
        <hr>
    
    {% endfor %}



</body>
</html>

songs/templates/songs/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <h1>수정 페이지</h1>
    
    <form action="{% url "songs:update" song.pk %}" method = "POST"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = '제출'>
    </form>
</head>
<body>
    
</body>
</html>